import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { SessionProvider } from "next-auth/react";
import NextAuth from "next-auth";
import { NextAuthProvider } from "./lib/next_auth/provider";
const NotoSansJp = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: "book commerce app",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${NotoSansJp.className} ${NotoSansJp.className} antialiased`}
      >
        <NextAuthProvider>
        <Header/>
        {children}

        </NextAuthProvider>
  
      </body>
    </html>
  );
}
